/**
 * Catálogo CIE-10, Capítulo VII: Enfermedades del ojo y sus anexos (H00-H59).
 * Generado a partir de data/CIE10_Capitulo_VII_Enfermedades_Oftalmologicas_H00-H59.json
 * (307 registros). Se corrigieron nombres truncados/partidos del documento fuente:
 * H02.7, H04.3, H06*, H19*, H28*, H36.0*, H54.3, H59.9.
 * Formato compacto: [código, nombre, índice de grupo]. Se carga bajo demanda (import dinámico).
 */

export const GRUPOS_CIE10: ReadonlyArray<{ codigo: string; nombre: string }> = [
  {
    "codigo": "H00-H06",
    "nombre": "Trastornos del párpado, aparato lagrimal y órbita"
  },
  {
    "codigo": "H10-H13",
    "nombre": "Trastornos de la conjuntiva"
  },
  {
    "codigo": "H15-H22",
    "nombre": "Trastornos de la esclerótica, córnea, iris y cuerpo ciliar"
  },
  {
    "codigo": "H25-H28",
    "nombre": "Trastornos del cristalino"
  },
  {
    "codigo": "H30-H36",
    "nombre": "Trastornos de la coroides y de la retina"
  },
  {
    "codigo": "H40-H42",
    "nombre": "Glaucoma"
  },
  {
    "codigo": "H43-H45",
    "nombre": "Trastornos del cuerpo vítreo y del globo ocular"
  },
  {
    "codigo": "H46-H48",
    "nombre": "Trastornos del nervio óptico y de las vías ópticas"
  },
  {
    "codigo": "H49-H52",
    "nombre": "Trastornos de los músculos oculares, del movimiento binocular, de la acomodación y de la refracción"
  },
  {
    "codigo": "H53-H54",
    "nombre": "Alteraciones de la visión y ceguera"
  },
  {
    "codigo": "H55-H59",
    "nombre": "Otros trastornos del ojo y sus anexos"
  }
];

export const DIAGNOSTICOS_CIE10: ReadonlyArray<readonly [string, string, number]> = [
  ["H00", "Orzuelo y calacio", 0],
  ["H00.0", "Orzuelo y otras inflamaciones profundas del párpado", 0],
  ["H00.1", "Calacio [chalazión]", 0],
  ["H01", "Otras inflamaciones del párpado", 0],
  ["H01.0", "Blefaritis", 0],
  ["H01.1", "Dermatosis no infecciosa del párpado", 0],
  ["H01.8", "Otras inflamaciones especificadas del párpado", 0],
  ["H01.9", "Inflamación del párpado, no especificada", 0],
  ["H02", "Otros trastornos de los párpados", 0],
  ["H02.0", "Entropión y triquiasis palpebral", 0],
  ["H02.1", "Ectropión del párpado", 0],
  ["H02.2", "Lagoftalmos", 0],
  ["H02.3", "Blefarocalasia", 0],
  ["H02.4", "Blefaroptosis", 0],
  ["H02.5", "Otros trastornos funcionales del párpado", 0],
  ["H02.6", "Xantelasma del párpado", 0],
  ["H02.7", "Otros trastornos degenerativos del párpado y del área periocular", 0],
  ["H02.8", "Otros trastornos especificados del párpado", 0],
  ["H02.9", "Trastorno del párpado, no especificado", 0],
  ["H03*", "Trastornos del párpado en enfermedades clasificadas en otra parte", 0],
  ["H03.0*", "Infección e infestación parasitarias del párpado en enfermedades clasificadas en otra parte", 0],
  ["H03.1*", "Compromiso del párpado en enfermedades infecciosas", 0],
  ["H03.8*", "Compromiso del párpado en enfermedades clasificadas en otra parte", 0],
  ["H04", "Trastornos del aparato lagrimal", 0],
  ["H04.0", "Dacrioadenitis", 0],
  ["H04.1", "Otros trastornos de la glándula lagrimal", 0],
  ["H04.2", "Epífora", 0],
  ["H04.3", "Inflamación aguda y la no especificada de las vías lagrimales", 0],
  ["H04.4", "Inflamación crónica de las vías lagrimales", 0],
  ["H04.5", "Estenosis e insuficiencia de las vías lagrimales", 0],
  ["H04.6", "Otros cambios de las vías lagrimales", 0],
  ["H04.8", "Otros trastornos especificados del aparato lagrimal", 0],
  ["H04.9", "Trastorno del aparato lagrimal, no especificado", 0],
  ["H05", "Trastornos de la órbita", 0],
  ["H05.0", "Inflamación aguda de la órbita", 0],
  ["H05.1", "Trastornos inflamatorios crónicos de la órbita", 0],
  ["H05.2", "Afecciones exoftálmicas", 0],
  ["H05.3", "Deformidad de la órbita", 0],
  ["H05.4", "Enoftalmia", 0],
  ["H05.5", "Retención de cuerpo extraño (antiguo), consecutiva a herida penetrante de la órbita", 0],
  ["H05.8", "Otros trastornos de la órbita", 0],
  ["H05.9", "Trastorno de la órbita, no especificado", 0],
  ["H06*", "Trastornos del sistema lagrimal y de la órbita en enfermedades clasificadas en otra parte", 0],
  ["H06.0*", "Trastornos del aparato lagrimal en enfermedades clasificadas en otra parte", 0],
  ["H06.1*", "Infección e infestación parasitarias de la órbita en enfermedades clasificadas en otra parte", 0],
  ["H06.2*", "Exoftalmia hipertiroidea (E05.–†)", 0],
  ["H06.3*", "Otros trastornos de la órbita en enfermedades clasificadas en otra parte", 0],
  ["H10", "Conjuntivitis", 1],
  ["H10.0", "Conjuntivitis mucopurulenta", 1],
  ["H10.1", "Conjuntivitis atópica aguda", 1],
  ["H10.2", "Otras conjuntivitis agudas", 1],
  ["H10.3", "Conjuntivitis aguda, no especificada", 1],
  ["H10.4", "Conjuntivitis crónica", 1],
  ["H10.5", "Blefaroconjuntivitis", 1],
  ["H10.8", "Otras conjuntivitis", 1],
  ["H10.9", "Conjuntivitis, no especificada", 1],
  ["H11", "Otros trastornos de la conjuntiva", 1],
  ["H11.0", "Pterigión", 1],
  ["H11.1", "Degeneraciones y depósitos conjuntivales", 1],
  ["H11.2", "Cicatrices conjuntivales", 1],
  ["H11.3", "Hemorragia conjuntival", 1],
  ["H11.4", "Otros trastornos vasculares y quistes conjuntivales", 1],
  ["H11.8", "Otros trastornos especificados de la conjuntiva", 1],
  ["H11.9", "Trastorno de la conjuntiva, no especificado", 1],
  ["H13*", "Trastornos de la conjuntiva en enfermedades clasificadas en otra parte", 1],
  ["H13.0*", "Infección filárica de la conjuntiva (B74.–†)", 1],
  ["H13.1*", "Conjuntivitis en enfermedades infecciosas y parasitarias", 1],
  ["H13.2*", "Conjuntivitis en otras enfermedades clasificadas en otra parte", 1],
  ["H13.3*", "Penfigoide ocular (L12.–†)", 1],
  ["H13.8*", "Otros trastornos de la conjuntiva en enfermedades clasificadas en otra parte", 1],
  ["H15", "Trastornos de la esclerótica", 2],
  ["H15.0", "Escleritis", 2],
  ["H15.1", "Episcleritis", 2],
  ["H15.8", "Otros trastornos de la esclerótica", 2],
  ["H15.9", "Trastorno de la esclerótica, no especificado", 2],
  ["H16", "Queratitis", 2],
  ["H16.0", "Úlcera de la córnea", 2],
  ["H16.1", "Otras queratitis superficiales sin conjuntivitis", 2],
  ["H16.2", "Queratoconjuntivitis", 2],
  ["H16.3", "Queratitis intersticial y profunda", 2],
  ["H16.4", "Neovascularización de la córnea", 2],
  ["H16.8", "Otras queratitis", 2],
  ["H16.9", "Queratitis, no especificada", 2],
  ["H17", "Opacidades y cicatrices corneales", 2],
  ["H17.0", "Leucoma adherente", 2],
  ["H17.1", "Otras opacidades centrales de la córnea", 2],
  ["H17.8", "Otras opacidades o cicatrices de la córnea", 2],
  ["H17.9", "Cicatriz u opacidad de la córnea, no especificada", 2],
  ["H18", "Otros trastornos de la córnea", 2],
  ["H18.0", "Pigmentaciones y depósitos en la córnea", 2],
  ["H18.1", "Queratopatía vesicular", 2],
  ["H18.2", "Otros edemas de la córnea", 2],
  ["H18.3", "Cambios en las membranas de la córnea", 2],
  ["H18.4", "Degeneración de la córnea", 2],
  ["H18.5", "Distrofia hereditaria de la córnea", 2],
  ["H18.6", "Queratocono", 2],
  ["H18.7", "Otras deformidades de la córnea", 2],
  ["H18.8", "Otros trastornos especificados de la córnea", 2],
  ["H18.9", "Trastorno de la córnea, no especificado", 2],
  ["H19*", "Trastornos de la esclerótica y de la córnea en enfermedades clasificadas en otra parte", 2],
  ["H19.0*", "Escleritis y episcleritis en enfermedades clasificadas en otra parte", 2],
  ["H19.1*", "Queratitis y queratoconjuntivitis por herpes simple (B00.5†)", 2],
  ["H19.2*", "Queratitis y queratoconjuntivitis en enfermedades infecciosas y parasitarias, clasificadas en otra parte", 2],
  ["H19.3*", "Queratitis y queratoconjuntivitis en otras enfermedades", 2],
  ["H19.8*", "Otros trastornos de la esclerótica y de la córnea en enfermedades clasificadas en otra parte", 2],
  ["H20", "Iridociclitis", 2],
  ["H20.0", "Iridociclitis aguda y subaguda", 2],
  ["H20.1", "Iridociclitis crónica", 2],
  ["H20.2", "Iridociclitis inducida por trastorno del cristalino", 2],
  ["H20.8", "Otras iridociclitis especificadas", 2],
  ["H20.9", "Iridociclitis, no especificada", 2],
  ["H21", "Otros trastornos del iris y del cuerpo ciliar", 2],
  ["H21.0", "Hifema", 2],
  ["H21.1", "Otros trastornos vasculares del iris y del cuerpo ciliar", 2],
  ["H21.2", "Degeneración del iris y del cuerpo ciliar", 2],
  ["H21.3", "Quiste del iris, del cuerpo ciliar y de la cámara anterior", 2],
  ["H21.4", "Membranas pupilares", 2],
  ["H21.5", "Otras adherencias y desgarros del iris y del cuerpo ciliar", 2],
  ["H21.8", "Otros trastornos especificados del iris y del cuerpo ciliar", 2],
  ["H21.9", "Trastorno del iris y del cuerpo ciliar, no especificado", 2],
  ["H22*", "Trastornos del iris y del cuerpo ciliar en enfermedades clasificadas en otra parte", 2],
  ["H22.0*", "Iridociclitis en enfermedades infecciosas y parasitarias", 2],
  ["H22.1*", "Iridociclitis en otras enfermedades clasificadas en otra parte", 2],
  ["H22.8*", "Otros trastornos del iris y del cuerpo ciliar en enfermedades clasificadas en otra parte", 2],
  ["H25", "Catarata senil", 3],
  ["H25.0", "Catarata senil incipiente", 3],
  ["H25.1", "Catarata senil nuclear", 3],
  ["H25.2", "Catarata senil, tipo morgagnian", 3],
  ["H25.8", "Otras cataratas seniles", 3],
  ["H25.9", "Catarata senil, no especificada", 3],
  ["H26", "Otras cataratas", 3],
  ["H26.0", "Catarata infantil, juvenil y presenil", 3],
  ["H26.1", "Catarata traumática", 3],
  ["H26.2", "Catarata complicada", 3],
  ["H26.3", "Catarata inducida por drogas", 3],
  ["H26.4", "Catarata residual", 3],
  ["H26.8", "Otras formas especificadas de catarata", 3],
  ["H26.9", "Catarata, no especificada", 3],
  ["H27", "Otros trastornos del cristalino", 3],
  ["H27.0", "Afaquia", 3],
  ["H27.1", "Luxación del cristalino", 3],
  ["H27.8", "Otros trastornos especificados del cristalino", 3],
  ["H27.9", "Trastorno del cristalino, no especificado", 3],
  ["H28*", "Catarata y otros trastornos del cristalino en enfermedades clasificadas en otra parte", 3],
  ["H28.0*", "Catarata diabética (E10–E14† con cuarto carácter común .3)", 3],
  ["H28.1*", "Catarata en otras enfermedades endocrinas, nutricionales y metabólicas clasificadas en otra parte", 3],
  ["H28.2*", "Catarata en otras enfermedades clasificadas en otra parte", 3],
  ["H28.8*", "Otros trastornos del cristalino en enfermedades clasificadas en otra parte", 3],
  ["H30", "Inflamación coriorretiniana", 4],
  ["H30.0", "Coriorretinitis focal", 4],
  ["H30.1", "Coriorretinitis diseminada", 4],
  ["H30.2", "Ciclitis posterior", 4],
  ["H30.8", "Otras coriorretinitis", 4],
  ["H30.9", "Coriorretinitis, no especificada", 4],
  ["H31", "Otros trastornos de la coroides", 4],
  ["H31.0", "Cicatrices coriorretinianas", 4],
  ["H31.1", "Degeneración coroidea", 4],
  ["H31.2", "Distrofia coroidea hereditaria", 4],
  ["H31.3", "Hemorragia y ruptura de la coroides", 4],
  ["H31.4", "Desprendimiento de la coroides", 4],
  ["H31.8", "Otros trastornos especificados de la coroides", 4],
  ["H31.9", "Trastorno de la coroides, no especificado", 4],
  ["H32*", "Trastornos coriorretinianos en enfermedades clasificadas en otra parte", 4],
  ["H32.0*", "Inflamación coriorretiniana en enfermedades infecciosas y parasitarias clasificadas en otra parte", 4],
  ["H32.8*", "Otros trastornos coriorretinianos en enfermedades clasificadas en otra parte", 4],
  ["H33", "Desprendimiento y desgarro de la retina", 4],
  ["H33.0", "Desprendimiento de la retina con ruptura", 4],
  ["H33.1", "Retinosquisis y quistes de la retina", 4],
  ["H33.2", "Desprendimiento seroso de la retina", 4],
  ["H33.3", "Desgarro de la retina sin desprendimiento", 4],
  ["H33.4", "Desprendimiento de la retina por tracción", 4],
  ["H33.5", "Otros desprendimientos de la retina", 4],
  ["H34", "Oclusión vascular de la retina", 4],
  ["H34.0", "Oclusión arterial transitoria de la retina", 4],
  ["H34.1", "Oclusión de la arteria central de la retina", 4],
  ["H34.2", "Otras formas de oclusión de la arteria de la retina", 4],
  ["H34.8", "Otras oclusiones vasculares retinianas", 4],
  ["H34.9", "Oclusión vascular retiniana, sin otra especificación", 4],
  ["H35", "Otros trastornos de la retina", 4],
  ["H35.0", "Retinopatías del fondo y cambios vasculares retinianos", 4],
  ["H35.1", "Retinopatía de la prematuridad", 4],
  ["H35.2", "Otras retinopatías proliferativas", 4],
  ["H35.3", "Degeneración de la mácula y del polo posterior del ojo", 4],
  ["H35.4", "Degeneración periférica de la retina", 4],
  ["H35.5", "Distrofia hereditaria de la retina", 4],
  ["H35.6", "Hemorragia retiniana", 4],
  ["H35.7", "Separación de las capas de la retina", 4],
  ["H35.8", "Otros trastornos especificados de la retina", 4],
  ["H35.9", "Trastorno de la retina, no especificado", 4],
  ["H36*", "Trastornos de la retina en enfermedades clasificadas en otra parte", 4],
  ["H36.0*", "Retinopatía diabética (E10–E14† con cuarto carácter común .3)", 4],
  ["H36.8*", "Otros trastornos de la retina en enfermedades clasificadas en otra parte", 4],
  ["H40", "Glaucoma", 5],
  ["H40.0", "Sospecha de glaucoma", 5],
  ["H40.1", "Glaucoma primario de ángulo abierto", 5],
  ["H40.2", "Glaucoma primario de ángulo cerrado", 5],
  ["H40.3", "Glaucoma secundario a traumatismo ocular", 5],
  ["H40.4", "Glaucoma secundario a inflamación ocular", 5],
  ["H40.5", "Glaucoma secundario a otros trastornos del ojo", 5],
  ["H40.6", "Glaucoma secundario a drogas", 5],
  ["H40.8", "Otros glaucomas", 5],
  ["H40.9", "Glaucoma, no especificado", 5],
  ["H42*", "Glaucoma en enfermedades clasificadas en otra parte", 5],
  ["H42.0*", "Glaucoma en enfermedades endocrinas, nutricionales y metabólicas, clasificadas en otra parte", 5],
  ["H42.8*", "Glaucoma en otras enfermedades clasificadas en otra parte", 5],
  ["H43", "Trastornos del cuerpo vítreo", 6],
  ["H43.0", "Prolapso del vítreo", 6],
  ["H43.1", "Hemorragia del vítreo", 6],
  ["H43.2", "Depósitos cristalinos en el cuerpo vítreo", 6],
  ["H43.3", "Otras opacidades vítreas", 6],
  ["H43.8", "Otros trastornos del cuerpo vítreo", 6],
  ["H43.9", "Trastorno del cuerpo vítreo, no especificado", 6],
  ["H44", "Trastornos del globo ocular", 6],
  ["H44.0", "Endoftalmitis purulenta", 6],
  ["H44.1", "Otras endoftalmitis", 6],
  ["H44.2", "Miopía degenerativa", 6],
  ["H44.3", "Otros trastornos degenerativos del globo ocular", 6],
  ["H44.4", "Hipotonía ocular", 6],
  ["H44.5", "Afecciones degenerativas del globo ocular", 6],
  ["H44.6", "Retención intraocular de cuerpo extraño magnético", 6],
  ["H44.7", "Retención intraocular de cuerpo extraño no magnético", 6],
  ["H44.8", "Otros trastornos del globo ocular", 6],
  ["H44.9", "Trastorno del globo ocular, no especificado", 6],
  ["H45*", "Trastornos del cuerpo vítreo y del globo ocular en enfermedades clasificadas en otra parte", 6],
  ["H45.0*", "Hemorragia del vítreo en enfermedades clasificadas en otra parte", 6],
  ["H45.1*", "Endoftalmitis en enfermedades clasificadas en otra parte", 6],
  ["H45.8*", "Otros trastornos del cuerpo vítreo y del globo ocular en enfermedades clasificadas en otra parte", 6],
  ["H46", "Neuritis óptica", 7],
  ["H47", "Otros trastornos del nervio óptico [II par] y de las vías ópticas", 7],
  ["H47.0", "Trastornos del nervio óptico, no clasificados en otra parte", 7],
  ["H47.1", "Papiledema, no especificado", 7],
  ["H47.2", "Atrofia óptica", 7],
  ["H47.3", "Otros trastornos del disco óptico", 7],
  ["H47.4", "Trastornos del quiasma óptico", 7],
  ["H47.5", "Trastornos de otras vías ópticas", 7],
  ["H47.6", "Trastornos de la corteza visual", 7],
  ["H47.7", "Trastorno de las vías ópticas, no especificado", 7],
  ["H48*", "Trastornos del nervio óptico y de las vías ópticas en enfermedades clasificadas en otra parte", 7],
  ["H48.0*", "Atrofia óptica en enfermedades clasificadas en otra parte", 7],
  ["H48.1*", "Neuritis retrobulbar en enfermedades clasificadas en otra parte", 7],
  ["H48.8*", "Otros trastornos del nervio óptico y de las vías ópticas en enfermedades clasificadas en otra parte", 7],
  ["H49", "Estrabismo paralítico", 8],
  ["H49.0", "Parálisis del nervio motor ocular común [III par]", 8],
  ["H49.1", "Parálisis del nervio patético [IV par]", 8],
  ["H49.2", "Parálisis del nervio motor ocular externo [VI par]", 8],
  ["H49.3", "Oftalmoplejía total (externa)", 8],
  ["H49.4", "Oftalmoplejía externa progresiva", 8],
  ["H49.8", "Otros estrabismos paralíticos", 8],
  ["H49.9", "Estrabismo paralítico, no especificado", 8],
  ["H50", "Otros estrabismos", 8],
  ["H50.0", "Estrabismo concomitante convergente", 8],
  ["H50.1", "Estrabismo concomitante divergente", 8],
  ["H50.2", "Estrabismo vertical", 8],
  ["H50.3", "Heterotropía intermitente", 8],
  ["H50.4", "Otras heterotropías o las no especificadas", 8],
  ["H50.5", "Heteroforia", 8],
  ["H50.6", "Estrabismo mecánico", 8],
  ["H50.8", "Otros estrabismos especificados", 8],
  ["H50.9", "Estrabismo, no especificado", 8],
  ["H51", "Otros trastornos de los movimientos binoculares", 8],
  ["H51.0", "Parálisis de la conjugación de la mirada", 8],
  ["H51.1", "Exceso e insuficiencia de la convergencia ocular", 8],
  ["H51.2", "Oftalmoplejía internuclear", 8],
  ["H51.8", "Otros trastornos especificados de los movimientos", 8],
  ["H51.9", "Trastorno del movimiento binocular, no especificado", 8],
  ["H52", "Trastornos de la acomodación y de la refracción", 8],
  ["H52.0", "Hipermetropía", 8],
  ["H52.1", "Miopía", 8],
  ["H52.2", "Astigmatismo", 8],
  ["H52.3", "Anisometropía y aniseiconía", 8],
  ["H52.4", "Presbicia", 8],
  ["H52.5", "Trastornos de la acomodación", 8],
  ["H52.6", "Otros trastornos de la refracción", 8],
  ["H52.7", "Trastorno de la refracción, no especificado", 8],
  ["H53", "Alteraciones de la visión", 9],
  ["H53.0", "Ambliopía ex anopsia", 9],
  ["H53.1", "Alteraciones visuales subjetivas", 9],
  ["H53.2", "Diplopía", 9],
  ["H53.3", "Otros trastornos de la visión binocular", 9],
  ["H53.4", "Defectos del campo visual", 9],
  ["H53.5", "Deficiencia de la visión cromática", 9],
  ["H53.6", "Ceguera nocturna", 9],
  ["H53.8", "Otras alteraciones visuales", 9],
  ["H53.9", "Alteración visual, no especificada", 9],
  ["H54", "Ceguera y disminución de la agudeza visual", 9],
  ["H54.0", "Ceguera de ambos ojos", 9],
  ["H54.1", "Ceguera de un ojo, visión subnormal del otro", 9],
  ["H54.2", "Visión subnormal de ambos ojos", 9],
  ["H54.3", "Disminución indeterminada de la agudeza visual en ambos ojos", 9],
  ["H54.4", "Ceguera de un ojo", 9],
  ["H54.5", "Visión subnormal de un ojo", 9],
  ["H54.6", "Disminución indeterminada de la agudeza visual de un ojo", 9],
  ["H54.7", "Disminución de la agudeza visual, sin especificación", 9],
  ["H55", "Nistagmo y otros movimientos oculares", 10],
  ["H57", "Otros trastornos del ojo y sus anexos", 10],
  ["H57.0", "Anomalías de la función pupilar", 10],
  ["H57.1", "Dolor ocular", 10],
  ["H57.8", "Otros trastornos especificados del ojo y sus anexos", 10],
  ["H57.9", "Trastorno del ojo y sus anexos, no especificado", 10],
  ["H58*", "Otros trastornos del ojo y sus anexos en enfermedades clasificadas en otra parte", 10],
  ["H58.0*", "Anomalías de la función pupilar en enfermedades clasificadas en otra parte", 10],
  ["H58.1*", "Alteraciones de la visión en enfermedades clasificadas en otra parte", 10],
  ["H58.8*", "Otros trastornos especificados del ojo en enfermedades clasificadas en otra parte", 10],
  ["H59", "Trastornos del ojo y sus anexos consecutivos a procedimientos, no clasificados en otra parte", 10],
  ["H59.0", "Queratopatía (bullosa afáquica) consecutiva a cirugía de catarata", 10],
  ["H59.8", "Otros trastornos del ojo y sus anexos, consecutivos a procedimientos", 10],
  ["H59.9", "Trastorno no especificado del ojo y sus anexos, consecutivo a procedimientos", 10],
];
